{% set name = "lleaves" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lleaves-{{ version }}.tar.gz
  sha256: b9e3c0b9e6896aa5bfe32192aba039063e3869dbedc44f5bec7a133078597fb1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - llvmlite >=0.36
    - numpy
    - python >=3.7

test:
  imports:
    - lleaves
    - lleaves.compiler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/siboehm/lleaves
  summary: LLVM-based compiler for LightGBM models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - siboehm
